name       : mate-terminal
version    : 1.27.0
release    : 17
source     :
    - https://github.com/mate-desktop/mate-terminal/releases/download/v1.27.0/mate-terminal-1.27.0.tar.xz : 42889c98045f011b7e633c2c1706dfc379d52c9c26aef386c8d6890c09d3681b
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
