name       : mate-terminal
version    : 1.18.1
release    : 6
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-terminal-1.18.1.tar.xz : 4135b2212a2ed5d6c20b645e17a76d814aa8212f68f83c0a67a9899680a930fe
license    : GPL-3.0
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
