name       : mate-terminal
version    : 1.22.0
release    : 10
source     :
    - https://github.com/mate-desktop//mate-terminal/archive/v1.22.0.tar.gz : 904b1bbda5c77f86a4ce2ab99c7994f782dbc85f9c6150f176eb99e52ed27929
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - itstool
    - mate-common
    - yelp-devel
    - yelp-tools
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
