name       : mate-terminal
version    : 1.24.0
release    : 12
source     :
    - https://github.com/mate-desktop/mate-terminal/archive/v1.24.0.tar.gz : 27a349c4f0175728ec44e2b557990d0de9cd2a8647cccba165aec44646ced60c
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - itstool
    - mate-common
    - yelp-devel
    - yelp-tools
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
