name       : mate-terminal
version    : 1.24.1
release    : 13
source     :
    - https://github.com/mate-desktop/mate-terminal/releases/download/v1.24.1/mate-terminal-1.24.1.tar.xz : 550d38f223d21ab12d39b00af6cd75f083d3790c38d53051537df2ac6a87be62
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
