name       : mate-terminal
version    : 1.22.1
release    : 11
source     :
    - https://github.com/mate-desktop/mate-terminal/archive/v1.22.1.tar.gz : 74e2f618e05db268cb9623df77e331be1bada0669a42c728b6186860e7a70e44
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - itstool
    - mate-common
    - yelp-devel
    - yelp-tools
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
