name       : mate-terminal
version    : 1.16.1
release    : 4
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-terminal-1.16.1.tar.xz : c032a11a6a4f5ccb84c3453cedba6c0b7100858cf1a2fa5d7f97173d4c33bccc
license    : GPL-3.0
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
