name       : mate-terminal
version    : 1.26.0
release    : 14
source     :
    - https://github.com/mate-desktop/mate-terminal/releases/download/v1.26.0/mate-terminal-1.26.0.tar.xz : 7727e714c191c3c55e535e30931974e229ca5128e052b62ce74dcc18f7eaaf22
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
