name       : mate-terminal
version    : 1.14.1
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-terminal-1.14.1.tar.xz : 248f8e4db544a76a521e7e80cceb3e6736b60c64880376b08f552cb66c378b29
license    : GPL-3.0
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
