name       : mate-terminal
version    : 1.18.2
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-terminal-1.18.2.tar.xz : ec9172fd1bd41938f79f2c4def4db31596eb74216151bc1dc18c7baa246b7214
license    : GPL-3.0
component  : desktop.mate
summary    : Mate Desktop Terminal Emulator
description: |
    Mate Desktop Terminal Emulator
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(sm)
    - pkgconfig(vte-2.91)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
